# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext    

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin: 
                        password: admin
                        roles: 'ROLE_ADMIN'
                
                

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/loisirs, roles: ROLE_ADMIN }
        
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/competences, roles: ROLE_ADMIN }
        
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/experiences, roles: ROLE_ADMIN }

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/formations, roles: ROLE_ADMIN }
