<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKp3nxdk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKp3nxdk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKp3nxdk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKp3nxdk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKp3nxdk\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kp3nxdk',
    'container.build_id' => '4f2b5dc1',
    'container.build_time' => 1523262666,
));
