<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFdbswnr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFdbswnr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFdbswnr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFdbswnr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFdbswnr\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Fdbswnr',
    'container.build_id' => 'afc1b5ba',
    'container.build_time' => 1523265761,
));
